apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-cicd-helloworld-example-qas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/viaacode/k8s-templatar_py-web.git
    targetRevision: main
    path: kustomize/cicd-helloworld-example/overlays/qas
  destination:
    server: https://kubernetes.default.svc
    namespace: playground
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
