apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cicd-helloworld-example-vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cicd-helloworld-example-vault
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "/playground/cicd-helloworld-example-prd"       # VAULT path: playground/cicd-helloworld-example
